export const environment = {
    production: false,
    LOGIN_API_URL: 'INSERT YOUR PROD HERE',   
    USERS_API_URL: 'INSERT YOUR PROD HERE',
    SERVICES_API_URL: 'INSERT YOUR PROD HERE',
    CLIENTS_API_URL: 'INSERT YOUR PROD HERE'
};